config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html
  resources :businesses
  post 'contact', to: 'businesses#contact'

  resources :about

  root 'businesses#index'
end

app/models/application_record.rb
# frozen_string_literal: true
# main class for models

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
# frozen_string_literal: true
# Business model

class Business < ApplicationRecord
  belongs_to :user
  belongs_to :community

  validates :name, :status, :community_id, :user_id, presence: true
end

app/models/community.rb
# frozen_string_literal: true
# Community model

class Community < ApplicationRecord
  has_many :businesses
end

app/models/user.rb
# frozen_string_literal: true
# USer model

class User < ApplicationRecord
  has_many :businesses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true
# App Controller

class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
# frozen_string_literal: true
# Business controller deals with requests involving business objects

class BusinessesController < ApplicationController
  include ApplicationHelper

  def index
    if params[:community_id]
      @businesses = Business.where(community_id: params[:community_id])
    elsif params[:name]
      @businesses = Business.where('name LIKE ?', "%#{params[:name]}%")
      @search = true
    else
      @businesses = Business.all
    end
  end

  def new
    if user_signed_in?
      @business = Business.new
    else
      redirect_to new_user_registration_path
    end
  end

  def create
    @business = Business.new(business_params)
    if @business.valid?
      @business.save
      redirect_to root_url, notice: 'Business Registered!'
    else
      puts @business.errors.details
      render :new, notice: 'Invalid Input'
    end
  end

  def show
    @business = Business.find(params[:id])
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(current_user.businesses.first.id)
    @business.update(business_params)
    if @business.valid?
      @business.save
      redirect_to root_url, notice: 'Business Updated!'
    else
      flash[:notice] = 'Invalid Input'
      render :edit
    end
  end

  def contact
    contact_business(params[:contact_string])
  end

  private

  def business_params
    params.require(:business).permit(:name, :status, :description,
      :community_id, :user_id, :delivery_contact, :pickup_contact,
      :relief_contact)
  end
end

app/controllers/communities_controller.rb
# frozen_string_literal: true
# community controller

class CommunitiesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true
# Application helpers can be called in controllers or models or rendering
module ApplicationHelper
  def browser_type
    agent = request.user_agent
    return 'tablet' if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return 'mobile' if agent =~ /Mobile/

    'desktop'
  end

  def contact_business(contact_string)
    if contact_string.include? 'http'
      redirect_to contact_string
    else
      redirect_to 'tel:' + contact_string
    end
  end
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true
# business helper methods
module BusinessesHelper
end

app/helpers/communities_helper.rb
# frozen_string_literal: true
# communities helepr methods
module CommunitiesHelper
end

app/views/businesses/edit.html.erb
<div class='business-form'>
  <%= form_with model: @business do |b| %>
    <h3>Name</h3>
    <p>Please enter the name of your business</p>
    <%= b.text_field :name %>
    <br>

    <h3>Status</h3>
    <p>Please enter the current status of your business.</p>
    <p>Examples could include "Open," "Pickup and Dropoff Only," or "Seeking Financial Support." Character limit 256.</p>
    <%= b.text_field :status %>
    <br>

    <h2>Delivery Contact</h2>
    <p>Please enter a phone number or URL by which users can place orders for delivery. Leave blank if your business is not offering delivery.</p>
    <%= b.text_field :delivery_contact %>
    <br>

    <h2>Curb-Side Pick-Up Contact</h2>
    <p>Please enter a phone number or URL by which users can place orders for takeout. Leave blank if your business is not offering curbside pick-up.</p>
    <%= b.text_field :pickup_contact %>
    <br>

    <h2>Relief Contact</h2>
    <p>Please enter a phone number or URL by which users can provide relief funding for your business. Leave blank if your business is not accepting relief funding.</p>
    <%= b.text_field :relief_contact %>
    <br>


    <h3>Further Information</h3>
    <p>Users will see this when they view your business's profile.</p>
    <p>This is a good place to add links to your website, phone numbers, links to crowdfunding profiles.</p>
    <p>Examples could include "Call this number to purchase a gift card" or "Our current business hours have changed," or any other details or resources you wish to provide. No character limit.</p>
    <%= b.text_area :description, cols: "100", rows: "10" %>
    <br>

    <h3>Community</h3>
    <p>Please select the community within Minneapolis where your business is located.</p>
    <%= b.select :community_id, options_for_select(Community.all.map { | c | [c.name, c.id] })%>

    <%= b.hidden_field :user_id, value: current_user.id %>
    <br>
    <div class="submit-btn">
      <%= b.submit "Submit" %>
    </div>
  <% end %>
</div>

app/views/businesses/index.html.erb

<div id="business-index">
  <h1>Minneapolis Business Index</h1>
  <% if @search %>
    <h3>Search Results:</h3>
  <% else %>
    <h3>Listed below is an index of all businesses that have been registered with the Minneapolis Small Business Relief Project.</h3>
    <p>Find out what services your local businesses are offering during this time and/or find out how you can help them make it through mandated closures.</p>
    <p>If you want to register your business with the Minneapolis Small Business Relief Project, select "Register Your Business from the Navigation Menu."</p>
    <br>
    <h3> Filter by Community </h3>
    <%= form_with(url: '/businesses', method: :get, class: "community-filter-form") do %>
      <%= select_tag :community_id, options_for_select(Community.all.map { | c | [c.name, c.id] }), include_blank: true %>
      <%= submit_tag 'Filter' %>
    <% end %>
    <br>
  <% end %>

  <table id='business-index-table'>
    <tr>
      <th> Business / Organization </th>
      <th> Resources </th>
      <% if browser_type == "mobile" or browser_type == "tablet" %>
      <% else %>
        <th> Community </th>
      <% end %>
    </tr>
    <% @businesses.each do |business| %>
      <tr>
        <td> <%= link_to business.name, business_path(business.id) %> </td>
        <% if business.delivery_contact.present? or business.pickup_contact.present? or business.relief_contact.present? %>
          <td>
            <div class="resource-container">
              <% if business.delivery_contact.present? %>
                <% if browser_type == "mobile" or browser_type == "tablet" %>
                  <%= button_to 'Delivery', contact_path(contact_string: business.delivery_contact), id: 'foodservice-contact-btn' %>
                <% else %>
                  <%= button_to 'Delivery: ' + business.delivery_contact, contact_path(contact_string: business.delivery_contact), id: 'foodservice-contact-btn' %>
                <% end %>
              <% end %>
              <% if business.pickup_contact.present? %>
                <% if browser_type == "mobile" or browser_type == "tablet" %>
                  <%= button_to 'Pick-Up', contact_path(contact_string: business.pickup_contact), id: 'foodservice-contact-btn' %>
                <% else %>
                  <%= button_to 'Pick-Up: ' + business.pickup_contact, contact_path(contact_string: business.pickup_contact), id: 'foodservice-contact-btn' %>
                <% end %>
              <% end %>
              <% if business.relief_contact.present? %>
                <% if browser_type == "mobile" or browser_type == "tablet" %>
                  <%= button_to "Relief", contact_path(contact_string: business.relief_contact), id:'relief-contact-btn' %>
                <% else %>
                  <%= button_to "Relief: " + business.relief_contact, contact_path(contact_string: business.relief_contact), id:'relief-contact-btn' %>
                <% end %>
              <% end %>
            </div>
          </td>
        <% end %>
        <div id="foodservice-contact"></div>
        <% if browser_type == "mobile" or browser_type == "tablet" %>
        <% else %>
          <td> <%= business.community.name %> </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/businesses/new.html.erb
<div class='business-form'>
  <%= form_with model: @business do |b| %>
    <h2>Name</h2>
    <p>Please enter the name of your business</p>
    <%= b.text_field :name %>
    <br>

    <h2>Status</h2>
    <p>Please enter the current status of your business.</p>
    <p>Examples could include "Open," "Pickup and Dropoff Only," or "Seeking Financial Support." Character limit 256.</p>
    <%= b.text_field :status %>
    <br>

    <h2>Delivery Contact</h2>
    <p>Please enter a phone number or URL by which users can place orders for delivery. Leave blank if your business is not offering delivery.</p>
    <%= b.text_field :delivery_contact %>
    <br>

    <h2>Curb-Side Pick-Up Contact</h2>
    <p>Please enter a phone number or URL by which users can place orders for takeout. Leave blank if your business is not offering curbside pick-up.</p>
    <%= b.text_field :pickup_contact %>
    <br>

    <h2>Relief Contact</h2>
    <p>Please enter a phone number or URL by which users can provide relief funding for your business. Leave blank if your business is not accepting relief funding.</p>
    <%= b.text_field :relief_contact %>
    <br>

    <h2>Further Information</h2>
    <p>Users will see this when they view your business's profile.</p>
    <p>This is a good place to add links to your website, phone numbers, links to crowdfunding profiles.</p>
    <p>Examples could include "Call this number to purchase a gift card" or "Our current business hours have changed," or any other details or resources you wish to provide. No character limit.</p>
    <%= b.text_area :description, cols: "100", rows: "10"  %>
    <br>

    <h2>Community</h2>
    <p>Please select the community within Minneapolis where your business is located.</p>
    <%= b.select :community_id, options_for_select(Community.all.map { | c | [c.name, c.id] }), include_blank: true %>

    <%= b.hidden_field :user_id, value: current_user.id %>
    <br>
    <div class="submit-btn">
      <%= b.submit "Submit" %>
    </div>
  <% end %>
</div>

app/views/businesses/show.html.erb
<div id='business-profile'>
  <h1> <%= @business.name %> </h1>

  <h3>Status</h3>
  <p> <%= @business.status %> </p>

  <h3>Resources</h3>
  <div class="resource-container">
    <% if @business.delivery_contact.present? %><%= button_to 'Delivery: ' + @business.delivery_contact, contact_path(contact_string: @business.delivery_contact), id: 'foodservice-contact-btn' %><% end %>
    <% if @business.pickup_contact.present? %><%= button_to 'Pick-Up: ' + @business.pickup_contact, contact_path(contact_string: @business.pickup_contact), id: 'foodservice-contact-btn' %><% end %>
    <% if @business.relief_contact.present? %><%= button_to "Relief: " + @business.relief_contact, contact_path(contact_string: @business.relief_contact), id:'relief-contact-btn' %><% end %>
  </div>

  <h3>Description</h3>
  <p> <%= @business.description %> </p>

  <h3>Community</h3>
  <p> <%= @business.community.name %> </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinneapolisSmallBusinessReliefProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script>
      function toggleDropdown() {
        var dropdown = document.getElementById("navbar-dropdown");
        dropdown.classList.toggle('open');
      }
    </script>
  </head>

  <body>
    <% if browser_type == "mobile" or browser_type == "tablet" %>
      <div class="navbar-mobile">
        <table style="width:100%">
          <tr>
            <td id="title-mobile">
              <%= link_to "Minneapolis Small Business Relief Project", root_path %>
            </td>
            <td id="hamburger-mobile">
              <button id="navbar-toggle-dropdown" onclick="toggleDropdown()"><i class="fa fa-bars"></i></button>
            </td>
          <tr>
            <td id="dropdown-container">
              <div id="navbar-dropdown">
                <ul>
                  <% if user_signed_in? %>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  <% else %>
                    <li><%= link_to "Log In", new_user_session_path %></li>
                  <% end %>
                <% unless current_page?(new_business_path) %>
                  <% if user_signed_in? and current_user.businesses.any? %>
                    <% unless current_page?(edit_business_path(current_user.businesses.first.id)) %>
                      <li><%= link_to "Edit Your Business Profile", edit_business_path(current_user.businesses.first.id) %></li>
                    <% end %>
                  <% else %>
                    <li><%= link_to "Register Your Business", new_business_path %></li>
                  <% end %>
                <% end %>
                <li>
                  <%= form_with('/businesses', method: :get) do %>
                    <%= text_field_tag :name, params[:name], value: 'Search' %>
                  <% end %>
                </li>
                </ul>
              </div>
          </td>
        </tr>
        </table>
      </div>
    <% else %>
      <div class="navbar">
        <table style="width:100%">
          <tr>
            <td id="title">
              <%= link_to "Minneapolis Small Business Relief Project", root_path %>
            </td>
            <td>
              <td>
                <%= form_tag('/businesses', method: :get) do %>
                  <%= text_field_tag :name, params[:name], value: 'Search' %>
                <% end %>
              </td>
              <% unless current_page?(new_business_path) %>
                <% if user_signed_in? and current_user.businesses.any? %>
                  <% unless current_page?(edit_business_path(current_user.businesses.first.id)) %>
                    <td><%= link_to "Edit Your Business Profile", edit_business_path(current_user.businesses.first.id) %></td>
                  <% end %>
                <% else %>
                  <td><%= link_to "Register Your Business", new_business_path %></td>
                <% end %>
              <% end %>
              <% if user_signed_in? %>
                <td id="registration-td"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></td>
              <% else %>
                <td id="registration-td"><%= link_to "Log In", new_user_session_path %></td>
              <% end %>
        </tr>
        </table>
      </div>
    <% end %>
    <% if flash[:notice] -%>
      <div class = "notice-box"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
    <br>
    <div class="footer">
      <p>Powered by PC Doodle 2020</p>
    </div>
  </body>
</html>